- hosts: all
  gather_facts: yes
  remote_user: root
  vars_files: 
    - secret.yml
  tasks:
    - name: Creating maprticket for root
      shell: "echo {{ item.name }} | maprlogin password"
      with_items: "{{ maprcred }}"      
      no_log: True

- hosts: all
  gather_facts: yes
  become: yes
  become_method: su
  become_user: mapr
  vars_files: 
    - secret.yml
  tasks:
    - name: Creating maprticket for mapr
      shell: "echo {{ item.name }} | maprlogin password"
      with_items: "{{ maprcred }}"      
      no_log: True